spring:
  application:
    name: authentication-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  config:
    label: main
server:
  port: 8088
