spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: runner-service
          uri: lb://runner-service
          predicates:
            - Path=/tusrunning/api/runners/**
          filters:
            - RewritePath=/tusrunning/api/(?<segment>.*), /api/${segment}

        - id: race-service
          uri: lb://race-service
          predicates:
            - Path=/tusrunning/api/races/**
          filters:
            - RewritePath=/tusrunning/api/(?<segment>.*), /api/${segment}

server:
  port: 9999
