spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9900/realms/microservices/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: runner-service
          uri: lb://runner-service
          predicates:
            - Path=/tusrunning/**
          filters:
            - RewritePath=/tusrunning/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: runnerCircuitBreaker
                fallbackUri: forward:/fallback/runners
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
resilience4j:
  circuitbreaker:
    instances:
      runnerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      raceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

server:
  port: 9999
