spring:
  application:
    name: gateway-service
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: runner-service
          uri: lb://runner-service
          predicates:
            - Path=/tusrunning/api/runners/**
          filters:
            - RewritePath=/tusrunning/api/(?<segment>.*), /api/${segment}
            - name: CircuitBreaker
              args:
                name: runnerCircuitBreaker
                fallbackUri: forward:/fallback/runners

resilience4j:
  circuitbreaker:
    instances:
      runnerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      raceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

server:
  port: 9999
