spring:
  application:
    name: race-service
  main:
    web-application-type: reactive

  zipkin:
    base-url: http://localhost:9411
    enabled: true
  security:
    oauth2:
       resourceserver:
         jwt:
           jwk-set-uri: http://localhost:9900/realms/microservices/protocol/openid-connect/certs
  sleuth:
    sampler:
      probability: 1.0

  r2dbc:
    url: r2dbc:mysql://localhost:3306/runnerdb
    username: runnerAdmin
    password: test1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl: auto=update
    show-sql: true

  config:
    label: main
server:
  port: 8081
