spring:
  application:
    name: race-service
  main:
    web-application-type: reactive
  security:
    oauth2:
       resourceserver:
         jwt:
           jwk-set-uri: http://localhost:9900/realms/microservices/protocol/openid-connect/certs
  r2dbc:
    url: r2dbc:mysql://localhost:3306/runnerdb
    username: runnerAdmin
    password: test1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl: auto=update
    show-sql: true

  config:
    label: main
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
