spring:
  application:
    name: runner-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9900/realms/microservices
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  r2dbc:
    url: r2dbc:mysql://localhost:3306/runnerdb
    username: runnerAdmin
    password=: test1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl: auto=update
# --- Show SQL Queries in Console (Optional) ---
    show-sql: true
  config:
    label: main
